{{- if and (eq .Values.hmac.mode "shared-secret") .Values.hmacSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provenance-enforcer.hmacSecretName" . }}
  namespace: {{ include "provenance-enforcer.namespace" . }}
{{- with .Values.hmacSecret.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.hmacSecret.labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
stringData:
  {{ include "provenance-enforcer.hmacSecretKeyField" . }}: {{ .Values.hmacSecret.value | quote }}
{{- end }}