{{- if and .Values.vault.enabled .Values.vault.tokenSecret.create (eq .Values.vault.authMethod "token") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.tokenSecret.name }}
  namespace: {{ include "provenance-enforcer.namespace" . }}
type: Opaque
stringData:
  token: {{ .Values.vault.tokenSecret.token | quote }}
{{- end }}